config/routes.rb
Rails.application.routes.draw do

  resources :thingies

  get 'welcome/index'

  root 'welcome#index'

end

app/models/thingy.rb
class Thingy < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/thingies_controller.rb
class ThingiesController < ApplicationController
  before_action :set_thingy, only: [:show, :edit, :update, :destroy]

  def index
    @thingies = Thingy.all
  end

  def show
  end

  def new
    @thingy = Thingy.new
  end

  def edit
  end

  def create
    @thingy = Thingy.new(thingy_params)

    respond_to do |format|
      if @thingy.save
        format.html { redirect_to @thingy, notice: 'Thingy was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @thingy.update(thingy_params)
        format.html { redirect_to @thingy, notice: 'Thingy was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @thingy.destroy
    respond_to do |format|
      format.html { redirect_to thingies_url, notice: 'Thingy was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_thingy
    @thingy = Thingy.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def thingy_params
    params.require(:thingy).permit(:name, :image)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thingies_helper.rb
module ThingiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CWFileUploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/thingies/_form.html.erb
<%= form_for(@thingy) do |f| %>
  <% if @thingy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thingy.errors.count, "error") %> prohibited this thingy from being saved:</h2>

      <ul>
      <% @thingy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section class="row">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, label: 'Thingy Name' %>
    </div>

    <div class="field">
      <p>Upload an image for this thingy.</p>
      <%= image_tag(@thingy.image.url) if @thingy.image? %>
      <%= f.file_field :image %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </section>
<% end %>

app/views/thingies/edit.html.erb
<h1>Editing thingy</h1>

<%= render 'form' %>

<%= link_to 'Show', @thingy %> |
<%= link_to 'Back', thingies_path %>

app/views/thingies/index.html.erb
<h1>The List of Thingies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thingies.each do |thingy| %>
      <tr>
        <td><%= image_tag thingy.image.small.url %></td>
        <td><%= thingy.name %></td>
        <td><%= link_to 'Show', thingy %></td>
        <td><%= link_to 'Edit', edit_thingy_path(thingy) %></td>
        <td><%= link_to 'Destroy', thingy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thingy', new_thingy_path %>

app/views/thingies/new.html.erb
<h1>New thingy</h1>

<%= render 'form' %>

<%= link_to 'Back', thingies_path %>

app/views/thingies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Thingy: <%= @thingy.name %></strong><br>

  <% if @thingy.image? %>
    <%= image_tag @thingy.image %>
  <% end %>
</p>

<%= link_to 'Edit', edit_thingy_path(@thingy) %> |
<%= link_to 'Back', thingies_path %>

app/views/welcome/index.html.erb
<h1>Welcome to CWImage_Uploader</h2>
<h2>A simple file uploader for images using Carrierwave</h2>
<p>Here, you can make 'Thingies'!</p>
<p>Thingies have two attributes: a name and an image.</p>
<%= link_to "Create a Thingy", new_thingy_path %> |
<%= link_to "Thingies Index", thingies_path %>